### ISSUE TITLE
New product editor (Beta) - Sync Failure When SOR Woocommerce

### ISSUE THREAD

**Issue by qasumitbagthariya** [woocommerce/woocommerce-square#199] opened 2024-08-14 13:57 UTC
### Describe the bug

Sync fails when the SOR is set to WooCommerce and the new Product Editor is enabled.

### To reproduce

1. Goto Woocommerce settings > Advanced > Enable New product editor 
1. Set the SOR to Square.
2. Create a variable product in the Square Dashboard.
3. Import the product.
4. After the variable product is imported successfully, change the SOR from Square to WooCommerce.
5. Run a manual sync.
6. See the error

**Screenshots**

![image](https://github.com/user-attachments/assets/6f4ebb13-71a6-43c9-ad9e-2f9165b8789a)

### Expected behavior

The manual sync should complete successfully without any errors, regardless of whether the SOR is set to WooCommerce or Square, when using the new product editor.

**Environment (please complete the following information):**
 - WordPress Version - 6.6.1
 - WooCommerce Version - 9.1.4 / 8.5.0
 - WooCommerce Square Plugin Version - 4.7.2

### Additional details

<details><summary>System status</summary>
  
  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
</details>

**Comment by Sidsector9** [comment] 2024-09-23 11:56
Closing as unable to reproduce this with Woo 9.3.2.

**Closed as completed by Sidsector9** 2024-09-23 11:56 UTC
Labels: priority: high, type: bug
